# Generated by Django 6.0.6 on 2026-06-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='empresa',
        ),
    ]
